### ISSUE TITLE
Fix the readme composer instructions

### ISSUE THREAD

**Issue by propagandaCreative** [yidas/google-maps-services-php#1]
The readme instructs the user to run the following command
`composer require yidas/google-map-sdk`

This is incorrect, as that package does not exist. The correct command is : 

`composer require yidas/google-maps-services`

**Comment by yidas** [comment]
Hi @propagandaCreative,

Thank you!

**Comment by propagandaCreative** [comment]
@yidas no thank you! The repo has been a lifesaver. 👍
