### ISSUE TITLE
Release required

### ISSUE THREAD

**Issue by dereuromark** [yidas/google-maps-services-php#11]
https://github.com/yidas/google-maps-services-php/compare/1.0.3...master

The composer fix seems to require a patch or minor release it seems.

**Comment by yidas** [comment]
Hi @dereuromark ,

Here is the [new release](https://github.com/yidas/google-maps-services-php/releases/tag/1.0.4).
Thank you for your reminder!

**Comment by dereuromark** [comment]
Are you still maintaining this library?
I was - based on PR activity - under the impression that a fork ( https://github.com/php-collective/google-maps-services/ ) is required..

**Comment by yidas** [comment]
Yeah. Thank you for your appreciation.
May I know what the PR activity is?

**Comment by dereuromark** [comment]
The open PRs on your repo
