### ISSUE TITLE
Add PHPDocs for various methods on Client class

### ISSUE THREAD

**Issue by omacranger** [yidas/google-maps-services-php#6]
It would be great if we could have PHPDocs for the various methods on the client class - which could provide some code completion for the likes of PHPStorm / intellisense. 

Something like below on the Client class would be pretty beneficial: 

```php
/**
 * Google Maps PHP Client
 *
 * @author  Nick Tsai <myintaer@gmail.com>
 * @version 1.0.0
 *
 * @method array distanceMatrix(string $origin, string $destination, array $params = [])
 ...
 */
class Client
```

I don't mind putting together a PR for this either.

**Comment by omacranger** [comment]
Actually, looks like this would be closed by #2

**Comment by yidas** [comment]
Hi @omacranger,

Thank you for you advice!

Please take the version [1.0.2](https://github.com/yidas/google-maps-services-php/releases/tag/1.0.2).

**Comment by omacranger** [comment]
Hey @yidas, appreciate it. Though it looks like the PHPDocs you have there aren't quite accurate. The first `$client` parameter you're passing automatically [here](https://github.com/yidas/google-maps-services-php/blob/master/src/Client.php#L219) - so that should be removed from all the PHPDocs since users wouldn't be expected to pass that manually.

**Comment by yidas** [comment]
Hi @omacranger,

I really appreciate your help!

Please take the version [1.0.3](https://github.com/yidas/google-maps-services-php/releases/tag/1.0.3).
